### ISSUE TITLE
Search for Plants by their Name

### ISSUE THREAD

**Issue by NicoleLinde** [NicoleLinde/capstone-project#2]

**Comment by NicoleLinde** [comment]
As a User I want to search for a plant's properties by the plant's name so that I can see easily if my plants fit the animal's needs.

**Acceptance Criteria**

- [ ] click on search icon opens the search bar
- [ ] user can search for plants
- [ ] user sees recommended search results while typing
- [ ] selecting a search result shows the plant card


**Complexity: XL**


**Tasks**

- [ ] new feature branch search-bar
- [ ] add search bar component
- [ ] implement search logic
- [ ] add tests
- [ ] add style-guidist component
