### ISSUE TITLE
navigate to extra functions via Navbar

### ISSUE THREAD

**Issue by NicoleLinde** [NicoleLinde/capstone-project#5]

**Comment by NicoleLinde** [comment]
As a user I want to be able to navigate easily so that I can have access to my favorites, Calendar and Home on one click.

**Acceptance criteria**

- [ ] click on icon to get access to extra other features
- [ ] icons appear active when clicked
- [ ] icons have different appearance when hovered
- [ ] Element hinzufügen

**Complexity: M**

**Tasks**

- [ ] add new feature- Branch Navbar
- [ ] add navbar- component
- [ ] implement Links
- [ ] implement hover and active- Style
